// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {ConfidentialNotes} from "../src/ConfidentialNotes.sol";
import {ConfidentialNotesVerifier} from "../src/ConfidentialNotesVerifier.sol";
import {PoseidonT3} from "../src/PoseidonT3.sol";

/// @title ConfidentialNotes Test — real Groth16 proof, zero-leak
/// @notice Tests the note-based system with 4 public signals (NO recipient).
///         The recipientViewKey is PRIVATE — never on-chain.
contract ConfidentialNotesTest is Test {
    ConfidentialNotes internal notes;
    ConfidentialNotesVerifier internal verifier;

    // ─── Proof constants (generated by scripts/zk_notes_prove.js) ────
    uint256 internal constant CN_NULLIFIER_HASH =
        12474780686017284981558011096150493561577049897177766358017712367231036756846;
    uint256 internal constant CN_NEW_COMMITMENT =
        13929342879246215742714996332281316098785822717664660472865995930974479050799;
    uint256 internal constant CN_ENCRYPTED_AMOUNT =
        11773251713321570768223971168099045156967731404017914016763351906581508186029;
    uint256 internal constant CN_ROOT = 9560046071838970884664866820431342388958052642239115089675197935631063605781;

    uint256 internal constant CN_PA0 = 9241206150219626306486955307759073015652734798430546130370865857024939570111;
    uint256 internal constant CN_PA1 = 16614426967177137867045138292675830827273917693977702580702572914356635488466;
    uint256 internal constant CN_PB00 = 2890268020526203409633274444703230414668957120373636869657257005706781454796;
    uint256 internal constant CN_PB01 = 18743304503151146199510449750756879789361761553304503589590001609047513057702;
    uint256 internal constant CN_PB10 = 12467270139419430538488814253318843047929099225510229425034376208109776670527;
    uint256 internal constant CN_PB11 = 2293716526416490689534582196191795960141546240079754951020549607196228430394;
    uint256 internal constant CN_PC0 = 11894462719790421844147087701144721266502269441701232225378030401717150584557;
    uint256 internal constant CN_PC1 = 15352650570925566462179028511665056204196065372474766095949228902496157318430;

    uint256 internal constant CN_NULLIFIER = 74565;
    uint256 internal constant CN_SECRET = 424080;
    uint256 internal constant CN_COMMITMENT =
        10668627541551714631760004857481015688483280564974508968977414304541315990345;

    function setUp() public {
        verifier = new ConfidentialNotesVerifier();
        notes = new ConfidentialNotes(address(verifier), address(this));
    }

    function _proof()
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub)
    {
        a = [CN_PA0, CN_PA1];
        b = [[CN_PB00, CN_PB01], [CN_PB10, CN_PB11]];
        c = [CN_PC0, CN_PC1];
        pub = [CN_NULLIFIER_HASH, CN_NEW_COMMITMENT, CN_ENCRYPTED_AMOUNT, CN_ROOT];
    }

    /// @notice Seed the first note (commitment) into the tree.
    function _seedForProof() internal {
        notes.seedNote(bytes32(CN_COMMITMENT));
    }

    // ═════════════════════════════════════════════════════════════════
    // Tests
    // ═════════════════════════════════════════════════════════════════

    /// @notice Seed creates the first note.
    function test_SeedNote() public {
        _seedForProof();
        assertEq(notes.noteCount(), 1, "note count should be 1");
        assertEq(uint256(notes.currentRoot()), CN_ROOT, "root should match proof root");
    }

    /// @notice The headline test: seed a note, then create a new note
    ///         via ZK proof. Zero value. No USDC. No recipient on-chain.
    function test_RealProofCreateNote() public {
        _seedForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub) = _proof();

        notes.createNote(a, b, c, pub);

        // Old note is spent.
        assertTrue(notes.nullifierHashes(CN_NULLIFIER_HASH), "old nullifier should be spent");

        // Two notes in the tree (seed + create).
        assertEq(notes.noteCount(), 2, "two notes should exist");
    }

    /// @notice Double-spend: creating a note twice reverts.
    function testRevert_DoubleSpend() public {
        _seedForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub) = _proof();

        notes.createNote(a, b, c, pub);

        vm.expectRevert(ConfidentialNotes.NullifierAlreadySpent.selector);
        notes.createNote(a, b, c, pub);
    }

    /// @notice Invalid proof reverts.
    function testRevert_InvalidProof() public {
        _seedForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub) = _proof();

        // Tamper with the proof.
        a[0] = a[0] + 1;

        vm.expectRevert(ConfidentialNotes.InvalidProof.selector);
        notes.createNote(a, b, c, pub);
    }
}
