// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {ConfidentialNotes} from "../src/ConfidentialNotes.sol";
import {ConfidentialNotesVerifier} from "../src/ConfidentialNotesVerifier.sol";
import {PoseidonT3} from "../src/PoseidonT3.sol";

/// @title ConfidentialNotes Test — real Groth16 proof, zero-leak
/// @notice Tests the note-based system with 4 public signals (NO recipient).
///         The recipientViewKey is PRIVATE — never on-chain.
contract ConfidentialNotesTest is Test {
    ConfidentialNotes internal notes;
    ConfidentialNotesVerifier internal verifier;

    // ─── Proof constants (generated by scripts/zk_notes_prove.js) ────
    uint256 internal constant CN_NULLIFIER_HASH =
        12474780686017284981558011096150493561577049897177766358017712367231036756846;
    uint256 internal constant CN_NEW_COMMITMENT =
        13929342879246215742714996332281316098785822717664660472865995930974479050799;
    uint256 internal constant CN_ENCRYPTED_AMOUNT =
        11773251713321570768223971168099045156967731404017914016763351906581508186029;
    uint256 internal constant CN_ROOT = 9560046071838970884664866820431342388958052642239115089675197935631063605781;

    uint256 internal constant CN_PA0 = 2813897648553205654103312168621802019144146499286875334932128839498064292663;
    uint256 internal constant CN_PA1 = 3968975247409091911050026992097055891512743997803565405041485725217231293403;
    uint256 internal constant CN_PB00 = 2104596634504677451070655360396033327483604479584365869674418538535427985438;
    uint256 internal constant CN_PB01 = 4806645326162525650213313475808899787423185585694543004424039215094944843193;
    uint256 internal constant CN_PB10 = 3186647578246098714816148983335865908553032830233885722541624230868451025769;
    uint256 internal constant CN_PB11 = 49686005470590134960816744600440122456550145278732012205436193457299157844;
    uint256 internal constant CN_PC0 = 17951808626055457337612301388545691053491923385310867849189156332172758563177;
    uint256 internal constant CN_PC1 = 1683305029229658194071713690525627044194374421539665084300200476775096357946;

    uint256 internal constant CN_NULLIFIER = 74565;
    uint256 internal constant CN_SECRET = 424080;
    uint256 internal constant CN_COMMITMENT =
        10668627541551714631760004857481015688483280564974508968977414304541315990345;

    function setUp() public {
        verifier = new ConfidentialNotesVerifier();
        notes = new ConfidentialNotes(address(verifier), address(this));
    }

    function _proof()
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub)
    {
        a = [CN_PA0, CN_PA1];
        b = [[CN_PB00, CN_PB01], [CN_PB10, CN_PB11]];
        c = [CN_PC0, CN_PC1];
        pub = [CN_NULLIFIER_HASH, CN_NEW_COMMITMENT, CN_ENCRYPTED_AMOUNT, CN_ROOT];
    }

    /// @notice Seed the first note (commitment) into the tree.
    function _seedForProof() internal {
        notes.seedNote(bytes32(CN_COMMITMENT));
    }

    // ═════════════════════════════════════════════════════════════════
    // Tests
    // ═════════════════════════════════════════════════════════════════

    /// @notice Seed creates the first note.
    function test_SeedNote() public {
        _seedForProof();
        assertEq(notes.noteCount(), 1, "note count should be 1");
        assertEq(uint256(notes.currentRoot()), CN_ROOT, "root should match proof root");
    }

    /// @notice The headline test: seed a note, then create a new note
    ///         via ZK proof. Zero value. No USDC. No recipient on-chain.
    function test_RealProofCreateNote() public {
        _seedForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub) = _proof();

        notes.createNote(a, b, c, pub);

        // Old note is spent.
        assertTrue(notes.nullifierHashes(CN_NULLIFIER_HASH), "old nullifier should be spent");

        // Two notes in the tree (seed + create).
        assertEq(notes.noteCount(), 2, "two notes should exist");
    }

    /// @notice Double-spend: creating a note twice reverts.
    function testRevert_DoubleSpend() public {
        _seedForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub) = _proof();

        notes.createNote(a, b, c, pub);

        vm.expectRevert(ConfidentialNotes.NullifierAlreadySpent.selector);
        notes.createNote(a, b, c, pub);
    }

    /// @notice Invalid proof reverts.
    function testRevert_InvalidProof() public {
        _seedForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[4] memory pub) = _proof();

        // Tamper with the proof.
        a[0] = a[0] + 1;

        vm.expectRevert(ConfidentialNotes.InvalidProof.selector);
        notes.createNote(a, b, c, pub);
    }
}
