// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {ConfidentialVault} from "../src/ConfidentialVault.sol";
import {Groth16Verifier as ConfidentialTransferVerifier} from "../src/ConfidentialTransferVerifier.sol";
import {PoseidonT3} from "../src/PoseidonT3.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/// @title ConfidentialVault Test — real Groth16 proof end-to-end
/// @notice Tests deposit, confidentialTransfer, and withdraw with a
///         real snarkjs-generated proof. The proof verifies:
///         - note ownership (nullifier + secret -> commitment in tree)
///         - amount > 0 (range proof)
///         - newCommitment = Poseidon(amount, blindingFactor)
///         - encryptedAmount = Poseidon(amount, recipient)
///
///         Proof constants generated by scripts/zk_confidential_prove.js
///         using snarkjs.groth16.exportSolidityCallData for correct
///         Fq2 point ordering.
contract ConfidentialVaultTest is Test {
    ConfidentialVault internal vault;
    ConfidentialTransferVerifier internal verifier;
    MockERC20 internal usdc;

    // ─── Public signals ──────────────────────────────────────────
    // [nullifierHash, newCommitment, encryptedAmount, root, recipient]
    uint256 internal constant CT_NULLIFIER_HASH =
        12474780686017284981558011096150493561577049897177766358017712367231036756846;
    uint256 internal constant CT_NEW_COMMITMENT =
        710974003287182530118946134879219445641299505588163469795801295662854105288;
    uint256 internal constant CT_ENCRYPTED_AMOUNT =
        11773251713321570768223971168099045156967731404017914016763351906581508186029;
    uint256 internal constant CT_ROOT = 9560046071838970884664866820431342388958052642239115089675197935631063605781;
    uint256 internal constant CT_RECIPIENT = 2827; // 0x0B0B

    // ─── Proof (from snarkjs.groth16.exportSolidityCallData) ──────
    // a = [PA0, PA1]
    uint256 internal constant CT_PA0 = 16219863235410729649940057458863783908146247950246675557767846119849452440605;
    uint256 internal constant CT_PA1 = 16220425109464472396535768809868853205128325593195628939382203985402604197228;

    // b = [[PB00, PB01], [PB10, PB11]] — Fq2, Solidity-ordered
    uint256 internal constant CT_PB00 = 13111067944410027311097130277171342957139695199904206518365617442850247628931;
    uint256 internal constant CT_PB01 = 3992484032326520797415814680173835847299460406429935081535390461692897817249;
    uint256 internal constant CT_PB10 = 10312285788647038453545629452811992471291538084879682093952818338756811511828;
    uint256 internal constant CT_PB11 = 21050572810533649275155426297671548698272683218368081350576519154776623643619;

    // c = [PC0, PC1]
    uint256 internal constant CT_PC0 = 17412345573325770157537898646848055001129133068648509141243596951315074661568;
    uint256 internal constant CT_PC1 = 9879266400956619603224813792219928167018583383000691094573283160167943063855;

    // ─── Witness values (for deposit) ────────────────────────────
    uint256 internal constant CT_AMOUNT = 1000000; // 1 USDC (6 dec)
    uint256 internal constant CT_NULLIFIER = 74565; // 0x12345
    uint256 internal constant CT_SECRET = 424080; // 0x67890
    uint256 internal constant CT_BLINDING = 11256099; // 0xabc123

    address internal constant RECIPIENT = address(0x0B0B);

    function setUp() public {
        usdc = new MockERC20();
        verifier = new ConfidentialTransferVerifier();
        vault = new ConfidentialVault(address(usdc), address(verifier), address(this));

        // Mint USDC to this test contract for deposits.
        usdc.mint(address(this), 10_000_000); // 10 USDC
        usdc.approve(address(vault), type(uint256).max);
    }

    /// @notice Build the proof arrays from the constants.
    function _proof()
        internal
        pure
        returns (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[5] memory pub)
    {
        a = [CT_PA0, CT_PA1];
        b = [[CT_PB00, CT_PB01], [CT_PB10, CT_PB11]];
        c = [CT_PC0, CT_PC1];
        pub = [CT_NULLIFIER_HASH, CT_NEW_COMMITMENT, CT_ENCRYPTED_AMOUNT, CT_ROOT, uint256(uint160(RECIPIENT))];
    }

    /// @notice Deposit a note with the exact same commitment the proof
    ///         was generated for. This makes the on-chain root match
    ///         the proof's root.
    function _depositForProof() internal {
        vault.deposit(CT_NULLIFIER, CT_SECRET, CT_AMOUNT, CT_BLINDING);
    }

    // ═════════════════════════════════════════════════════════════════
    // Deposit tests
    // ═════════════════════════════════════════════════════════════════

    function test_DepositCreatesNote() public {
        _depositForProof();
        assertEq(vault.nextLeafIndex(), 1, "leaf index should be 1");
        assertEq(uint256(vault.currentRoot()), CT_ROOT, "root should match proof root");
        assertEq(usdc.balanceOf(address(vault)), CT_AMOUNT, "vault should hold USDC");
    }

    function testRevert_DepositZeroAmount() public {
        vm.expectRevert(ConfidentialVault.AmountZero.selector);
        vault.deposit(CT_NULLIFIER, CT_SECRET, 0, CT_BLINDING);
    }

    // ═════════════════════════════════════════════════════════════════
    // Withdraw tests
    // ═════════════════════════════════════════════════════════════════

    /// @notice The headline test: deposit, then withdraw with a real
    ///         Groth16 proof. USDC is sent to the stealth recipient.
    function test_RealProofWithdraw() public {
        _depositForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[5] memory pub) = _proof();

        uint256 recipientBefore = usdc.balanceOf(RECIPIENT);
        vault.withdraw(a, b, c, pub, CT_AMOUNT);
        uint256 recipientAfter = usdc.balanceOf(RECIPIENT);

        assertEq(recipientAfter - recipientBefore, CT_AMOUNT, "recipient should receive USDC");
        assertTrue(vault.nullifierHashes(CT_NULLIFIER_HASH), "nullifier should be spent");
    }

    function testRevert_DoubleSpendWithdraw() public {
        _depositForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[5] memory pub) = _proof();

        vault.withdraw(a, b, c, pub, CT_AMOUNT);

        vm.expectRevert(ConfidentialVault.NullifierAlreadySpent.selector);
        vault.withdraw(a, b, c, pub, CT_AMOUNT);
    }

    function testRevert_WrongAmount() public {
        _depositForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[5] memory pub) = _proof();

        vm.expectRevert(ConfidentialVault.InvalidProof.selector);
        vault.withdraw(a, b, c, pub, CT_AMOUNT + 1);
    }

    // ═════════════════════════════════════════════════════════════════
    // Confidential transfer tests
    // ═════════════════════════════════════════════════════════════════

    /// @notice Confidential transfer: old note nullified, new note
    ///         created. NO USDC moves — pure ZK state transition.
    function test_RealProofConfidentialTransfer() public {
        _depositForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[5] memory pub) = _proof();

        uint256 vaultBalanceBefore = usdc.balanceOf(address(vault));

        vault.confidentialTransfer(a, b, c, pub);

        // No USDC should have moved.
        assertEq(usdc.balanceOf(address(vault)), vaultBalanceBefore, "no USDC should move");

        // Old note is spent.
        assertTrue(vault.nullifierHashes(CT_NULLIFIER_HASH), "old nullifier should be spent");

        // Two leaves: deposit + transfer.
        assertEq(vault.nextLeafIndex(), 2, "two leaves should exist");

        // Encrypted amount stored for new commitment.
        assertEq(
            uint256(vault.noteEncryptedAmounts(bytes32(CT_NEW_COMMITMENT))),
            CT_ENCRYPTED_AMOUNT,
            "encrypted amount should be stored"
        );
    }

    function testRevert_DoubleSpendTransfer() public {
        _depositForProof();

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c, uint256[5] memory pub) = _proof();

        vault.confidentialTransfer(a, b, c, pub);

        vm.expectRevert(ConfidentialVault.NullifierAlreadySpent.selector);
        vault.confidentialTransfer(a, b, c, pub);
    }

    // ═════════════════════════════════════════════════════════════════
    // Admin tests
    // ═════════════════════════════════════════════════════════════════

    function test_OwnerWithdrawUSDC() public {
        _depositForProof();
        uint256 before = usdc.balanceOf(address(this));
        vault.withdrawUSDC(address(this), CT_AMOUNT);
        uint256 after_ = usdc.balanceOf(address(this));
        assertEq(after_ - before, CT_AMOUNT, "owner should recover USDC");
    }

    function testRevert_NonOwnerWithdraw() public {
        _depositForProof();
        vm.prank(address(0xBEEF));
        vm.expectRevert();
        vault.withdrawUSDC(address(0xBEEF), CT_AMOUNT);
    }
}
