// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script, console} from "forge-std/Script.sol";
import {ConfidentialVault} from "../src/ConfidentialVault.sol";
import {Groth16Verifier as ConfidentialTransferVerifier} from "../src/ConfidentialTransferVerifier.sol";

interface IERC20 {
    function approve(address, uint256) external returns (bool);
}

/**
 * DeployConfidentialVault.s.sol
 *
 * Deploys the ConfidentialTransferVerifier + ConfidentialVault on Base
 * mainnet. The vault wraps USDC at 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913.
 * Owner = deployer (0x3f44A645...).
 *
 * Run:
 *   forge script script/DeployConfidentialVault.s.sol \
 *     --rpc-url $BASE_RPC_URL \
 *     --private-key $DEPLOYER_PRIVATE_KEY \
 *     --broadcast --slow
 */
contract DeployConfidentialVault is Script {
    // Base mainnet USDC (6 decimals)
    address constant USDC = 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913;

    function run() external {
        uint256 pk = vm.envUint("DEPLOYER_PRIVATE_KEY");
        address deployer = vm.addr(pk);

        vm.startBroadcast(pk);

        // 1. Deploy the Groth16 verifier (auto-generated by snarkjs).
        ConfidentialTransferVerifier v = new ConfidentialTransferVerifier();
        console.log("ConfidentialTransferVerifier deployed at:", address(v));

        // 2. Deploy the vault.
        ConfidentialVault vault = new ConfidentialVault(USDC, address(v), deployer);
        console.log("ConfidentialVault deployed at:", address(vault));

        vm.stopBroadcast();
    }
}
