// Generate a PoseidonT3 Solidity library (2-input Poseidon, BN254) whose
// constants come from the VENDORED circomlib poseidon_constants.circom — the
// same file withdraw.circom compiles against — so on-chain hash === in-circuit
// hash. The algorithm is the OPTIMIZED circomlib Poseidon (sparse partial
// rounds via S + P matrix), verified bit-for-bit against circomlibjs in
// scripts/verify_poseidon_ref.js (poseidon(1,2) and two more vectors match).
//
//   node scripts/gen_poseidon_sol.js <circuits_dir> <out.sol>
//
// Why this emission shape (NOT `uint256[N] internal constant`): solc 0.8.x
// rejects fixed-size value-type arrays as `constant` (compiler error 9259,
// "Only constants of value type and byte array type are implemented"), which
// fails `forge build` outright. Each constant array is therefore emitted as a
// `pure` function returning a `memory` array LITERAL — the one form solc
// accepts for big arrays — allocated once per Poseidon call. Gas is acceptable
// for P3.3 (the gate is a real Groth16 proof, not gas-opt); P3.4/P3.6 may
// repack if per-withdraw gas needs it.
const fs = require("fs");
const path = require("path");

const circuitsDir = process.argv[2];
const outFile = process.argv[3];

// --- constant extraction (per-function grouping, hex-literal match) ---
function extractAll() {
  const consts = fs.readFileSync(path.join(circuitsDir, "circomlib/circuits/poseidon_constants.circom"), "utf8");
  const re = /function\s+(\w+)\s*\(\s*t\s*\)|(\b(?:if|else if)\b)\s*\(\s*t==(\d+)\s*\)/g;
  const byFn = {};
  let m, curFn = null;
  const order = [];
  while ((m = re.exec(consts)) !== null) {
    if (m[1]) { curFn = m[1]; if (!byFn[curFn]) { byFn[curFn] = []; order.push(curFn); } continue; }
    byFn[curFn].push({ t: Number(m[3]), s: m.index });
  }
  const out = {};
  for (const fn of order) {
    const arr = byFn[fn];
    out[fn] = {};
    for (let i = 0; i < arr.length; i++) {
      const end = i + 1 < arr.length ? arr[i + 1].s : consts.length;
      const body = consts.slice(arr[i].s, end);
      out[fn][arr[i].t] = (body.match(/0x[0-9a-fA-F]+/g) || []).map(BigInt);
    }
  }
  return out;
}

const ALL = extractAll();
const t = 3, nRoundsF = 8, nRoundsP = 57;
const C = ALL.POSEIDON_C[t];
const Mflat = ALL.POSEIDON_M[t];
const Pflat = ALL.POSEIDON_P[t];
const S = ALL.POSEIDON_S[t];
if (C.length !== t * nRoundsF + nRoundsP) throw new Error(`C len ${C.length} != ${t * nRoundsF + nRoundsP}`);
if (Mflat.length !== t * t) throw new Error(`M len ${Mflat.length}`);
if (Pflat.length !== t * t) throw new Error(`P len ${Pflat.length}`);
if (S.length !== nRoundsP * (2 * t - 1)) throw new Error(`S len ${S.length}`);
const M = [], P = [];
for (let i = 0; i < t; i++) { M.push(Mflat.slice(i * t, (i + 1) * t)); P.push(Pflat.slice(i * t, (i + 1) * t)); }

const hex = (v) => "0x" + v.toString(16);

// Emit a big constant array as a `pure` function returning a `memory` literal,
// wrapping lines at ~88 chars so diffs stay readable.
function emitArrayFn(name, len, vals, commentLines) {
  const lines = [];
  for (const c of commentLines) lines.push(`    /// @dev ${c}`);
  lines.push(`    function ${name}() internal pure returns (uint256[${len}] memory r) {`);
  // Pack the literal array tokens, wrapping when the line would exceed ~92 chars.
  let row = "        r = [";
  for (let i = 0; i < len; i++) {
    let tok = hex(vals[i]) + (i < len - 1 ? "," : "");
    if (row.length + tok.length + 1 > 92) { lines.push(row); row = "            "; }
    row += tok + " ";
  }
  row = row.replace(/\s+$/, "") + "];";
  lines.push(row);
  lines.push("    }");
  return lines;
}

const L = [];
L.push("// SPDX-License-Identifier: MIT");
L.push("/*");
L.push(" * PoseidonT3 — 2-input Poseidon hash over BN254 (circomlib parameters).");
L.push(" * GENERATED by scripts/gen_poseidon_sol.js from the constants in the VENDORED");
L.push(" * circomlib/circuits/poseidon_constants.circom — the SAME constants withdraw.circom");
L.push(" * compiles against — so on-chain hash === in-circuit hash. The optimized circomlib");
L.push(` * structure: ${nRoundsF} full rounds + ${nRoundsP} sparse partial rounds, width t=3.`);
L.push(" * Attribution: iden3/circomlib (MIT). Not hand-rolled.");
L.push(" *");
L.push(" * Verified: scripts/verify_poseidon_ref.js reproduces circomlibjs on");
L.push(" *   poseidon(0,0), poseidon(1,0), poseidon(1,2) — this Solidity is a mechanical");
L.push(" *   port of that verified reference. Lane order: state = [0, a, b] (PoseidonEx).");
L.push(" *");
L.push(" * Emission note: round constants / matrices are emitted as `pure` functions");
L.push(" *   returning memory-array literals (NOT `uint256[N] constant`) because solc 0.8.x");
L.push(" *   rejects fixed-size value-type arrays as `constant` (compiler error 9259).");
L.push(" */");
L.push("pragma solidity ^0.8.20;");
L.push("");
L.push("library PoseidonT3 {");
L.push("    /// @dev BN254 scalar field modulus.");
L.push("    uint256 internal constant Q = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;");
L.push("");
L.push(...emitArrayFn("C", C.length, C, [
  `Round constants C (flat, ${C.length}). Layout per circomlib: [0..t-1]=ark0, then`,
  `(nRoundsF/2-1) full rounds of t each, then a P-round's t, then nRoundsP single`,
  `partial-round constants, then the final (nRoundsF/2-1) full rounds of t each.`
]));
L.push("");
L.push(...emitArrayFn("M0", t, M[0], [`MDS matrix M row 0 (M[j][i] — col i indexes output i; row j). t*t row-major.`]));
L.push(...emitArrayFn("M1", t, M[1], [`MDS matrix M row 1.`]));
L.push(...emitArrayFn("M2", t, M[2], [`MDS matrix M row 2.`]));
L.push("");
L.push(...emitArrayFn("P0", t, P[0], [`M^(nRoundsP) product matrix P row 0 (boundary full round uses P, not M).`]));
L.push(...emitArrayFn("P1", t, P[1], [`M^(nRoundsP) product matrix P row 1.`]));
L.push(...emitArrayFn("P2", t, P[2], [`M^(nRoundsP) product matrix P row 2.`]));
L.push("");
L.push(...emitArrayFn("S", S.length, S, [
  `Sparse partial-round constants S (flat, ${S.length}). Per round r:`,
  `out[0] = sum_i S[r*(2t-1)+i]*in[i]; out[i>0] = in[i] + S[r*(2t-1)+(t-1)+i]*in[0].`,
  `For t=3 each round consumes S[r*5+0..4]: [0..2] scale the dot for out[0],`,
  `[3] scales in[0] into out[1], [4] scales in[0] into out[2].`
]));
L.push("");
L.push("    function pow5(uint256 a) internal pure returns (uint256) {");
L.push("        unchecked {");
L.push("            uint256 a2 = mulmod(a, a, Q);");
L.push("            return mulmod(a2, mulmod(a2, a, Q), Q);");
L.push("        }");
L.push("    }");
L.push("");
L.push(`    /// @dev circomlib Mix — out[i] = sum_j M[j][i]*in[j] (column i of M dotted`);
L.push(`    ///      with the input). M0()/M1()/M2() are M ROWS, so out[i] reads column i`);
L.push(`    ///      = [M0[i], M1[i], M2[i]]. Verified vs scripts/verify_poseidon_ref.js.`);
L.push(`    function mixFull(uint256 a, uint256 b, uint256 c, uint256[${t}] memory m0,`);
L.push(`        uint256[${t}] memory m1, uint256[${t}] memory m2)`);
L.push(`        internal pure returns (uint256 s0, uint256 s1, uint256 s2)`);
L.push("    {");
L.push("        unchecked {");
L.push("            // out[i] = in[0]*M[0][i] + in[1]*M[1][i] + in[2]*M[2][i]  (column i).");
L.push("            s0 = addmod(addmod(mulmod(a, m0[0], Q), mulmod(b, m1[0], Q), Q), mulmod(c, m2[0], Q), Q);");
L.push("            s1 = addmod(addmod(mulmod(a, m0[1], Q), mulmod(b, m1[1], Q), Q), mulmod(c, m2[1], Q), Q);");
L.push("            s2 = addmod(addmod(mulmod(a, m0[2], Q), mulmod(b, m1[2], Q), Q), mulmod(c, m2[2], Q), Q);");
L.push("        }");
L.push("    }");
L.push("");
L.push("    /// @dev circomlib MixS — sparse partial-round mix. base = r*(2t-1)=r*5.");
L.push("    ///      o0 = a*s0+b*s1+c*s2; o1 = b + a*s3; o2 = c + a*s4 (s0..s4 = S[base..base+4]).");
L.push("    function mixS(uint256 a, uint256 b, uint256 c, uint256 s0, uint256 s1, uint256 s2,");
L.push("        uint256 s3, uint256 s4) internal pure returns (uint256 o0, uint256 o1, uint256 o2)");
L.push("    {");
L.push("        unchecked {");
L.push("            o0 = addmod(addmod(mulmod(a, s0, Q), mulmod(b, s1, Q), Q), mulmod(c, s2, Q), Q);");
L.push("            o1 = addmod(b, mulmod(a, s3, Q), Q);");
L.push("            o2 = addmod(c, mulmod(a, s4, Q), Q);");
L.push("        }");
L.push("    }");
L.push("");
L.push("    /// @dev 2-input Poseidon. Returns poseidon(a, b) in the BN254 scalar field.");
L.push("    ///      Mechanically ported from the verified scripts/verify_poseidon_ref.js:");
L.push("    ///      state=[0,a,b], ark0, (nRoundsF/2-1) full M rounds, one P round, nRoundsP");
L.push("    ///      sparse rounds, (nRoundsF/2-1) full M rounds, final sigma + M-column-0 dot.");
L.push("    function poseidon(uint256 a, uint256 b) internal pure returns (uint256) {");
L.push("        unchecked {");
L.push("            uint256 s0 = uint256(0); uint256 s1 = a; uint256 s2 = b;");
L.push("            // Load constants once per call (memory literals — see emission note).");
L.push(`            uint256[${C.length}] memory _c = C();`);
L.push(`            uint256[${S.length}] memory _s = S();`);
L.push(`            uint256[${t}] memory _m0 = M0(); uint256[${t}] memory _m1 = M1(); uint256[${t}] memory _m2 = M2();`);
L.push(`            uint256[${t}] memory _p0 = P0(); uint256[${t}] memory _p1 = P1(); uint256[${t}] memory _p2 = P2();`);
L.push("            // ark[0]: s_i += C[i].");
L.push("            s0 = addmod(s0, _c[0], Q); s1 = addmod(s1, _c[1], Q); s2 = addmod(s2, _c[2], Q);");
// First nRoundsF/2 - 1 full rounds (sigma all, ark offset (r+1)*t, mix M).
for (let r = 0; r < nRoundsF / 2 - 1; r++) {
  const off = (r + 1) * t;
  L.push(`            // full round r=${r} (sigma -> ark@${off} -> mix M)`);
  L.push("            s0 = pow5(s0); s1 = pow5(s1); s2 = pow5(s2);");
  L.push(`            s0 = addmod(s0, _c[${off}], Q); s1 = addmod(s1, _c[${off + 1}], Q); s2 = addmod(s2, _c[${off + 2}], Q);`);
  L.push("            (s0, s1, s2) = mixFull(s0, s1, s2, _m0, _m1, _m2);");
}
// The P-boundary full round: sigma all, ark offset (nRoundsF/2)*t, mix P.
{
  const off = (nRoundsF / 2) * t;
  L.push(`            // P-boundary full round (sigma -> ark@${off} -> mix P)`);
  L.push("            s0 = pow5(s0); s1 = pow5(s1); s2 = pow5(s2);");
  L.push(`            s0 = addmod(s0, _c[${off}], Q); s1 = addmod(s1, _c[${off + 1}], Q); s2 = addmod(s2, _c[${off + 2}], Q);`);
  L.push("            (s0, s1, s2) = mixFull(s0, s1, s2, _p0, _p1, _p2);");
}
// Partial rounds: sigma s0, +C[(nRoundsF/2+1)*t + r] into s0, mixS.
{
  const base = (nRoundsF / 2 + 1) * t;
  L.push(`            // ${nRoundsP} sparse partial rounds (sigma s0 -> +C@[${base}+r] -> mixS)`);
  for (let r = 0; r < nRoundsP; r++) {
    const sb = r * (2 * t - 1);
    L.push("            s0 = pow5(s0);");
    L.push(`            s0 = addmod(s0, _c[${base + r}], Q);`);
    L.push(`            (s0, s1, s2) = mixS(s0, s1, s2, _s[${sb}], _s[${sb + 1}], _s[${sb + 2}], _s[${sb + 3}], _s[${sb + 4}]);`);
  }
}
// Last nRoundsF/2 - 1 full rounds.
{
  const base = (nRoundsF / 2 + 1) * t + nRoundsP;
  for (let r = 0; r < nRoundsF / 2 - 1; r++) {
    const off = base + r * t;
    L.push(`            // final full round r=${r} (sigma -> ark@${off} -> mix M)`);
    L.push("            s0 = pow5(s0); s1 = pow5(s1); s2 = pow5(s2);");
    L.push(`            s0 = addmod(s0, _c[${off}], Q); s1 = addmod(s1, _c[${off + 1}], Q); s2 = addmod(s2, _c[${off + 2}], Q);`);
    L.push("            (s0, s1, s2) = mixFull(s0, s1, s2, _m0, _m1, _m2);");
  }
}
// Final sigma all + mixLast[0] (dot M column 0).
L.push("            // final sigma + mixLast[0] (dot M column 0)");
L.push("            s0 = pow5(s0); s1 = pow5(s1); s2 = pow5(s2);");
L.push("            return addmod(addmod(mulmod(s0, _m0[0], Q), mulmod(s1, _m1[0], Q), Q), mulmod(s2, _m2[0], Q), Q);");
L.push("        }");
L.push("    }");
L.push("}");

fs.writeFileSync(outFile, L.join("\n") + "\n");
process.stderr.write(`wrote ${L.length} lines to ${outFile} (C=${C.length} S=${S.length})\n`);
