// P3.3-C end-to-end prover. Builds the SAME incremental Poseidon Merkle tree
// the on-chain PrivacyPool.sol uses (pure-JS Poseidon verified bit-for-bit vs
// circomlibjs in verify_poseidon_ref.js — no circomlibjs dependency), inserts a
// commitment = Poseidon(nullifier, secret), captures the Merkle path, and
// writes the witness input for withdraw.circom. The witness + Groth16 proof
// are then generated by snarkjs (run in WSL where the toolchain lives) and the
// resulting proof/public signals are emitted as a Solidity test-constants file.
//
// Why pure-JS (not circomlibjs): circomlibjs is not installed on the native
// Windows node, only in WSL. verify_poseidon_ref.js already proves our pure-JS
// Poseidon === circomlibjs on the known vectors, so the tree it builds here
// matches the wasm's in-circuit Poseidon. The wasm still computes the final
// witness (so the constraint system is authoritative); we only build the tree
// off-chain to know which root/path to feed it.
//
//   node scripts/zk_prove_e2e.js <circuits_dir> <build_dir> <out_dir>
//
// Produces in <out_dir>: input.json (witness input), tree.json (root, path,
// commitment, nullifier, secret, leafIndex — everything the Foundry test needs
// to replay the same deposits on-chain).
const fs = require("fs");
const path = require("path");

const circuitsDir = process.argv[2];
const buildDir = process.argv[3];
const outDir = process.argv[4];

// ─── Poseidon (pure JS, BN254) — mirror of verify_poseidon_ref.js ──────────
const Q = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001n;
const mod = (a, b = Q) => ((a % b) + b) % b;

function extractAll() {
  const consts = fs.readFileSync(path.join(circuitsDir, "circomlib/circuits/poseidon_constants.circom"), "utf8");
  const re = /function\s+(\w+)\s*\(\s*t\s*\)|(\b(?:if|else if)\b)\s*\(\s*t\s*==\s*(\d+)\s*\)/g;
  const byFn = {};
  let m, curFn = null;
  const order = [];
  while ((m = re.exec(consts)) !== null) {
    if (m[1]) { curFn = m[1]; if (!byFn[curFn]) { byFn[curFn] = []; order.push(curFn); } continue; }
    byFn[curFn].push({ t: Number(m[3]), s: m.index });
  }
  const out = {};
  for (const fn of order) {
    const arr = byFn[fn];
    out[fn] = {};
    for (let i = 0; i < arr.length; i++) {
      const end = i + 1 < arr.length ? arr[i + 1].s : consts.length;
      const body = consts.slice(arr[i].s, end);
      out[fn][arr[i].t] = (body.match(/0x[0-9a-fA-F]+/g) || []).map(BigInt);
    }
  }
  return out;
}

const ALL = extractAll();
const t = 3, nRoundsF = 8, nRoundsP = 57;
const C = ALL.POSEIDON_C[t];
const Mflat = ALL.POSEIDON_M[t];
const Pflat = ALL.POSEIDON_P[t];
const S = ALL.POSEIDON_S[t];
const M = [], P = [];
for (let i = 0; i < t; i++) { M.push(Mflat.slice(i * t, (i + 1) * t)); P.push(Pflat.slice(i * t, (i + 1) * t)); }

const sigma = (x) => { const x2 = mod(x * x); return mod(x2 * x2 * x); };
function mixFull(state, matrix) {
  const out = new Array(t);
  for (let i = 0; i < t; i++) {
    let acc = 0n;
    for (let j = 0; j < t; j++) acc = mod(acc + matrix[j][i] * state[j]); // column i
    out[i] = acc;
  }
  return out;
}
function mixS(state, r) {
  const base = r * (2 * t - 1);
  const out = new Array(t);
  let acc = 0n;
  for (let i = 0; i < t; i++) acc = mod(acc + S[base + i] * state[i]);
  out[0] = acc;
  for (let i = 1; i < t; i++) out[i] = mod(state[i] + S[base + (t - 1) + i] * state[0]);
  return out;
}
function poseidon2(a, b) {
  let st = [0n, a, b];
  st = st.map((v, i) => mod(v + C[i]));
  for (let r = 0; r < nRoundsF / 2 - 1; r++) {
    st = st.map(sigma);
    st = st.map((v, i) => mod(v + C[(r + 1) * t + i]));
    st = mixFull(st, M);
  }
  st = st.map(sigma);
  st = st.map((v, i) => mod(v + C[(nRoundsF / 2) * t + i]));
  st = mixFull(st, P);
  for (let r = 0; r < nRoundsP; r++) {
    st[0] = sigma(st[0]);
    st[0] = mod(st[0] + C[(nRoundsF / 2 + 1) * t + r]);
    st = mixS(st, r);
  }
  for (let r = 0; r < nRoundsF / 2 - 1; r++) {
    st = st.map(sigma);
    st = st.map((v, i) => mod(v + C[(nRoundsF / 2 + 1) * t + nRoundsP + r * t + i]));
    st = mixFull(st, M);
  }
  st = st.map(sigma);
  let acc = 0n;
  for (let j = 0; j < t; j++) acc = mod(acc + M[j][0] * st[j]);
  return acc;
}
// 1-input Poseidon (nullifierHash = Poseidon(nullifier)). circomlib Poseidon(1)
// uses t=2 (1 input + capacity 1) and its own constants — but the circuit's
// Poseidon(1) is the SAME optimized hash with t=2. We extract t=2 constants.
const C2 = ALL.POSEIDON_C[2];
const M2flat = ALL.POSEIDON_M[2];
const P2flat = ALL.POSEIDON_P[2];
const S2 = ALL.POSEIDON_S[2];
const t2 = 2, nRoundsF2 = 8, nRoundsP2 = 56; // N_ROUNDS_P for t=2 in circomlib
const M2 = [], P2 = [];
for (let i = 0; i < t2; i++) { M2.push(M2flat.slice(i * t2, (i + 1) * t2)); P2.push(P2flat.slice(i * t2, (i + 1) * t2)); }
function mixFull2(state, matrix) {
  const out = new Array(t2);
  for (let i = 0; i < t2; i++) {
    let acc = 0n;
    for (let j = 0; j < t2; j++) acc = mod(acc + matrix[j][i] * state[j]);
    out[i] = acc;
  }
  return out;
}
function mixS2(state, r) {
  const base = r * (2 * t2 - 1);
  const out = new Array(t2);
  let acc = 0n;
  for (let i = 0; i < t2; i++) acc = mod(acc + S2[base + i] * state[i]);
  out[0] = acc;
  for (let i = 1; i < t2; i++) out[i] = mod(state[i] + S2[base + (t2 - 1) + i] * state[0]);
  return out;
}
function poseidon1(a) {
  let st = [0n, a];
  st = st.map((v, i) => mod(v + C2[i]));
  for (let r = 0; r < nRoundsF2 / 2 - 1; r++) {
    st = st.map(sigma);
    st = st.map((v, i) => mod(v + C2[(r + 1) * t2 + i]));
    st = mixFull2(st, M2);
  }
  st = st.map(sigma);
  st = st.map((v, i) => mod(v + C2[(nRoundsF2 / 2) * t2 + i]));
  st = mixFull2(st, P2);
  for (let r = 0; r < nRoundsP2; r++) {
    st[0] = sigma(st[0]);
    st[0] = mod(st[0] + C2[(nRoundsF2 / 2 + 1) * t2 + r]);
    st = mixS2(st, r);
  }
  for (let r = 0; r < nRoundsF2 / 2 - 1; r++) {
    st = st.map(sigma);
    st = st.map((v, i) => mod(v + C2[(nRoundsF2 / 2 + 1) * t2 + nRoundsP2 + r * t2 + i]));
    st = mixFull2(st, M2);
  }
  st = st.map(sigma);
  let acc = 0n;
  for (let j = 0; j < t2; j++) acc = mod(acc + M2[j][0] * st[j]);
  return acc;
}

// ─── Incremental Merkle tree (mirrors PrivacyPool.sol _insert) ─────────────
const DEPTH = 20;
const zeros = [0n];
for (let l = 1; l <= DEPTH; l++) zeros.push(poseidon2(zeros[l - 1], zeros[l - 1]));
const filledSubtrees = zeros.slice(0, DEPTH).map((z) => z); // start at zeros[l]
let currentRoot = zeros[DEPTH];
let nextLeafIndex = 0;

function insert(leaf) {
  const index = nextLeafIndex;
  let current = leaf;
  for (let l = 0; l < DEPTH; l++) {
    const isRight = ((index >> l) & 1) === 1;
    if (isRight) {
      const left = filledSubtrees[l];
      filledSubtrees[l] = zeros[l];
      current = poseidon2(left, current);
    } else {
      filledSubtrees[l] = current;
      current = poseidon2(current, zeros[l]);
    }
  }
  currentRoot = current;
  nextLeafIndex = index + 1;
  return index;
}

function insertWithPathClean(leaf) {
  const index = nextLeafIndex;
  let current = leaf;
  const elements = [];
  const indices = [];
  for (let l = 0; l < DEPTH; l++) {
    const isRight = ((index >> l) & 1) === 1;
    indices.push(isRight ? 1 : 0);
    if (isRight) {
      const sibling = filledSubtrees[l]; // capture BEFORE reset
      elements.push(sibling);
      filledSubtrees[l] = zeros[l];
      current = poseidon2(sibling, current);
    } else {
      elements.push(zeros[l]);
      filledSubtrees[l] = current;
      current = poseidon2(current, zeros[l]);
    }
  }
  currentRoot = current;
  nextLeafIndex = index + 1;
  return { index, elements, indices };
}

// ─── Build the deposit + witness input ────────────────────────────────────
const nullifier = 0x12345n;
const secret = 0x67890n;
const commitment = poseidon2(nullifier, secret);
const nullifierHash = poseidon1(nullifier);

const { index, elements, indices } = insertWithPathClean(commitment);
const root = currentRoot;

// Sanity: recompute the root from the path (independent check).
let check = commitment;
for (let l = 0; l < DEPTH; l++) {
  check = indices[l] === 0 ? poseidon2(check, elements[l]) : poseidon2(elements[l], check);
}
if (check !== root) throw new Error(`root mismatch: path-recompute ${check} != tree ${root}`);

// recipient = a fixed address the Foundry test will use.
const recipient = BigInt("0x" + "B0B".padStart(40, "0")); // 0x0...0B0B

const input = {
  root: root.toString(),
  recipient: recipient.toString(),
  nullifier: nullifier.toString(),
  secret: secret.toString(),
  merklePathElements: elements.map((x) => x.toString()),
  merklePathIndices: indices.map((x) => x.toString()),
};

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "input.json"), JSON.stringify(input, null, 2));
fs.writeFileSync(
  path.join(outDir, "tree.json"),
  JSON.stringify(
    {
      nullifier: nullifier.toString(),
      secret: secret.toString(),
      commitment: commitment.toString(),
      nullifierHash: nullifierHash.toString(),
      root: root.toString(),
      leafIndex: index,
      merklePathElements: elements.map((x) => x.toString()),
      merklePathIndices: indices.map((x) => x.toString()),
      recipient: recipient.toString(),
      recipientHex: "0x" + recipient.toString(16).padStart(40, "0"),
      zeros: zeros.map((x) => x.toString()),
    },
    null,
    2
  )
);

console.log("commitment    :", commitment.toString());
console.log("nullifierHash :", nullifierHash.toString());
console.log("root          :", root.toString());
console.log("leafIndex     :", index);
console.log("recipient     :", "0x" + recipient.toString(16).padStart(40, "0"));
console.log("path-recompute root matches:", check === root);
console.log("wrote input.json + tree.json to", outDir);
